Parameters:
  MyKey:
    Description: ssh key for ec2 instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

Resources:
  EmrLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub emr-log-bucket-${AWS::AccountId}-${AWS::StackName}

  EmrServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub emr-service-role-${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: elasticmapreduce.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceRole

  EmrJobFlowRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub emr-job-flow-role-${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforEC2Role

  EmrJobFlowInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub emr-job-flow-instance-profile-${AWS::StackName}
      Path: /
      Roles:
        - !Ref EmrJobFlowRole

  EmrCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Name: !Sub emr-cluster-${AWS::StackName}
      ServiceRole: !Ref EmrServiceRole
      JobFlowRole: !Ref EmrJobFlowInstanceProfile
      ReleaseLabel: emr-5.34.0
      VisibleToAllUsers: true
      LogUri: !Sub s3://aws-logs-${AWS::AccountId}-${AWS::Region}/elasticmapreduce/
      Applications:
        - Name: Hadoop
        - Name: Zeppelin
        - Name: Spark
      Instances:
        Ec2KeyName: !Ref MyKey
        # AdditionalMasterSecurityGroups:
        #   - !Ref EmrClusterSecurityGroup
        MasterInstanceGroup:
          InstanceCount: 1
          InstanceType: m3.xlarge
          Market: ON_DEMAND
          Name: Master
        CoreInstanceGroup:
          InstanceCount: 1
          InstanceType: m3.xlarge
          Market: ON_DEMAND
          Name: Core


Outputs:
  # PublicId:
  #   Value:
  #     !GetAtt MyEC2Instance.PublicIp
  EmrDNS:
    Value:
      !GetAtt EmrCluster.MasterPublicDNS